name: Gerar Documentação com IA

on:
  push:
    branches:
      - main
      - dev

jobs:
  gerar-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Python (OpenAI client)
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip install openai

      - name: Gerar documentação com IA
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Procurando arquivos modificados..."
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\\.php$')

          for FILE in $MODIFIED_FILES; do
            echo "\nAnalisando: $FILE"
            CODE=$(cat $FILE)
            PROMPT="Gere uma documentação PHPDoc para as funções presentes no seguinte código PHP: $CODE"

            python3 -c "
import openai
import os
openai.api_key = os.getenv('OPENAI_API_KEY')
resp = openai.ChatCompletion.create(
  model='gpt-4',
  messages=[
    {'role': 'user', 'content': \"$PROMPT\"}
  ]
)
print(resp['choices'][0]['message']['content'])
"
          done
